const CONFIG = {
    titleWeb: "Châu Anh",
    introTitle: 'Tôi Biết bà Bi hóng cái web lắm rùi nhma',
    introDesc: Tiện thể nghe nói bà cx thích nên tôi làm tạm cái này nha,
    btnIntro: 'Tiếp Tục Ha',
    title: 'Phải chăng bà Bi đã muốn xem cái web lắm rùi',
    desc: 'Nhưng mà tôi phải đợi có dịp mới tặng được cơ ',
    btnYes: 'Ocie biết rùi',
    btnNo: 'Không Quan Tâm',
    question: 'Vậy cho hỏi bà có thể quên đi cái web tôi làm cho Lam được không',
    btnReply: 'Gửi cho Kizt',
    reply: 'Ocie tôi sẽ đợi màaaaaaaaa',
    mess: 'Tôi biết mà =)))) , Bi là một người rất giỏi chờ đợi',
    messDesc: 'Sắp rồi, sắp có web rồi trời ơi.',
    btnAccept: 'Biết rồi màa :_))',
}
